### PR TITLE
backup-stream: fix some bugs in log backup

### LINKED ISSUE #34098: Remove temporary files after restore succeed.

### PR DESCRIPTION
**Pull request by 3pointer**
Signed-off-by: 3pointer <luancheng@pingcap.com>

### What is changed and how it works?

Issue Number: Close https://github.com/pingcap/tidb/issues/34098

What's Changed:
1. implement clear rpc for sst_services.
2. fix the bug that repeated download kv file in apply.
3. run make clippy.

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
with https://github.com/pingcap/tidb/pull/34103/files, I checked the `v1` directory has been removed. and in tikv.log we can see
[2022/04/20 16:04:58.121 +08:00] [INFO] [sst_importer.rs:117] ["directory \"/home/cluster/restore/tidb-data-restore/tikv-20260/import/v1\" has been removed"]

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
If this PR will be picked to release branch, then a release note is probably required.
```

### CODE REVIEW

File: components/sst_importer/src/sst_importer.rs [hunk 1]
```diff
@@ -274,7 +286,24 @@ impl SSTImporter {
...
+            None
+        };
+        if path.save.exists() {
+            return Ok(path.save);
+        }
+
+        let lock = self
+            .file_locks
+            .entry(name.to_string())
+            .or_insert(Mutex::new(()));
```
Comment (YuJuncen) [inline components/sst_importer/src/sst_importer.rs]:
```suggestion
            .or_default();
```

I am afraid that if we call `Mutex::new` each time, we may trigger some system calls each time too, which would be a little slow.🤔

**Review by YuJuncen — APPROVED** [review]
lgtm

File: components/sst_importer/src/sst_importer.rs (hunk 1 above)
Comment (3pointer) [reply components/sst_importer/src/sst_importer.rs]: Since Mutex is meaningless. I 'll remove it.

File: components/sst_importer/src/sst_importer.rs [hunk 2]
```diff
@@ -324,18 +358,25 @@ impl SSTImporter {
...
             event_iter.next()?;
 
+            INPORTER_APPLY_COUNT.with_label_values(&["key_meet"]).inc();
             let ts = Key::decode_ts_from(event_iter.key())?;
             if ts > TimeStamp::new(restore_ts) {
                 // we assume the keys in file are sorted by ts.
                 // so if we met the key not satisfy the ts.
                 // we can easily filter the remain keys.
+                ts_not_expected += 1;
                 break;
```
Comment (joccau) [inline components/sst_importer/src/sst_importer.rs]: Maybe the keys in the file are not sorted by ts.

**Review by joccau — APPROVED** [review]
LGTM
